package Data;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patrick
 */
import java.awt.Component;

import javax.swing.JOptionPane;

public class CreateCourse extends javax.swing.JFrame {

    /**
     * Creates new form CreateCourse
     */
    public CreateCourse() {
        initComponents();
        
        DBManager dbm = new DBManager();
        Building b;
        boolean valid = true;
        
        while(valid==true){
            b = dbm.getNextBuilding();
            if(b==null){
                valid = false;
            }
            else{
                cmbFirstPref.addItem(b.getName());
                cmbSecondPref.addItem(b.getName());
                cmbThirdPref.addItem(b.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftxtCapacity = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        ckbMonday = new javax.swing.JCheckBox();
        ckbTuesday = new javax.swing.JCheckBox();
        ckbWednesday = new javax.swing.JCheckBox();
        ckbThursday = new javax.swing.JCheckBox();
        ckbFriday = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cmbFirstPref = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbSecondPref = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmbThirdPref = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        ckbNoPrefrence = new javax.swing.JCheckBox();
        btnReturn = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Course");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Information"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Course Name:");

        txtName.setToolTipText("The name of the new course.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Capacity:");

        ftxtCapacity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Meeting days"));

        ckbMonday.setText("Monday");
        ckbMonday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbMondayStateChanged(evt);
            }
        });

        ckbTuesday.setText("Tuesday");
        ckbTuesday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbTuesdayStateChanged(evt);
            }
        });

        ckbWednesday.setText("Wednesday");
        ckbWednesday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbWednesdayStateChanged(evt);
            }
        });

        ckbThursday.setText("Thursday");
        ckbThursday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbThursdayStateChanged(evt);
            }
        });

        ckbFriday.setText("Friday");
        ckbFriday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbFridayStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbMonday)
                    .addComponent(ckbThursday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ckbTuesday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbWednesday))
                    .addComponent(ckbFriday))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMonday)
                    .addComponent(ckbTuesday)
                    .addComponent(ckbWednesday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbThursday)
                    .addComponent(ckbFriday)))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("First Prefrence:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Second Prefrence:");

        cmbSecondPref.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Third Prefrence:");

        cmbThirdPref.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Type of Class:");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal Classroom", "Lecture Hall", "Laboratory" }));
        cmbType.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Course Number:");

        ckbNoPrefrence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbNoPrefrence.setText("No Prefrence");
        ckbNoPrefrence.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbNoPrefrenceStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumber)
                            .addComponent(ftxtCapacity)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckbNoPrefrence)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbFirstPref, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSecondPref, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbThirdPref, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(ckbNoPrefrence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbFirstPref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbSecondPref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbThirdPref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog((Component) null, "Are you sure you want to return? Unsaved data will be lost.",
        "alert", JOptionPane.OK_CANCEL_OPTION);
        if(result == 0){
            this.dispose();
        }
        
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        
        DBManager dbm = new DBManager();
        int features[] = new int[] {0, 0, 0};
        int days[] = new int[] {0, 0, 0, 0, 0, 0, 0};
        
        String Name = txtName.getText();
        
        int Capacity = Integer.parseInt(ftxtCapacity.getText());
        int PrefOne = cmbFirstPref.getSelectedIndex();
        int PrefTwo = cmbSecondPref.getSelectedIndex();
        int PrefThree = cmbThirdPref.getSelectedIndex();
        String CourseNumber = txtNumber.getText();
        int Type = cmbType.getSelectedIndex();
        
        features[Type] = 1;
        
        Course c = dbm.newCourse();
        
        if(ckbMonday.isSelected()){
            days[0] = 1;
        }
        if(ckbTuesday.isSelected()){
            days[1] = 1;
        }
        if(ckbWednesday.isSelected()){
            days[2] = 1;
        }
        if(ckbThursday.isSelected()){
            days[3] = 1;
        }
        if(ckbFriday.isSelected()){
            days[4] = 1;
        }
               
        String[] ids = dbm.getAllBuildingIDs();
        String[] Prefrences = new String[3];
        
        if(ckbNoPrefrence.isSelected()){
            Prefrences[0] = null;
            Prefrences[1] = null;
            Prefrences[2] = null;
        }        
        
        Prefrences[0] = ids[PrefOne];
        if(PrefTwo == 0)
            Prefrences[1] = null;
        else        
            Prefrences[1] = ids[PrefTwo - 1];
        
        if(PrefThree == 0)
            Prefrences[2] = null;
        else
            Prefrences[2] = ids[PrefThree - 1];
        
        c.setCourseName(Name);
        c.setCapacity(Capacity);
        c.setFeatures(features);
        c.setDays(days);
        c.setCourseNumber(CourseNumber);
        c.setPreferences(Prefrences);
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void ckbNoPrefrenceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbNoPrefrenceStateChanged
        // TODO add your handling code here:
        boolean checked = ckbNoPrefrence.isSelected();
        if(checked){
            cmbFirstPref.setEnabled(false);
            cmbSecondPref.setEnabled(false);
            cmbThirdPref.setEnabled(false);
        }
        else{
            cmbFirstPref.setEnabled(true);
            cmbSecondPref.setEnabled(true);
            cmbThirdPref.setEnabled(true);
        }
    }//GEN-LAST:event_ckbNoPrefrenceStateChanged

    private void ckbMondayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbMondayStateChanged
        // TODO add your handling code here:
        boolean checked = ckbMonday.isSelected();
        if(checked){
            ckbTuesday.setEnabled(false);
            ckbThursday.setEnabled(false);
        }
        else if(!checked && !ckbWednesday.isSelected() && !ckbFriday.isSelected()){
            ckbTuesday.setEnabled(true);
            ckbThursday.setEnabled(true);
        }
    }//GEN-LAST:event_ckbMondayStateChanged

    private void ckbTuesdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbTuesdayStateChanged
        boolean checked = ckbTuesday.isSelected();
        if(checked){
            ckbMonday.setEnabled(false);
            ckbWednesday.setEnabled(false);
            ckbFriday.setEnabled(false);
        }
        else if(!checked && !ckbThursday.isSelected()){
            ckbMonday.setEnabled(true);
            ckbWednesday.setEnabled(true);
            ckbFriday.setEnabled(true);
        }
    }//GEN-LAST:event_ckbTuesdayStateChanged

    private void ckbWednesdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbWednesdayStateChanged
        boolean checked = ckbWednesday.isSelected();
        if(checked){
            ckbTuesday.setEnabled(false);
            ckbThursday.setEnabled(false);
        }
        else if(!checked && !ckbMonday.isSelected() && !ckbFriday.isSelected()){
            ckbTuesday.setEnabled(true);
            ckbThursday.setEnabled(true);
        }
    }//GEN-LAST:event_ckbWednesdayStateChanged

    private void ckbThursdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbThursdayStateChanged
        boolean checked = ckbThursday.isSelected();
        if(checked){
            ckbMonday.setEnabled(false);
            ckbWednesday.setEnabled(false);
            ckbFriday.setEnabled(false);
        }
        else if(!checked && !ckbTuesday.isSelected()){
            ckbMonday.setEnabled(true);
            ckbWednesday.setEnabled(true);
            ckbFriday.setEnabled(true);
        }
    }//GEN-LAST:event_ckbThursdayStateChanged

    private void ckbFridayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbFridayStateChanged
        boolean checked = ckbFriday.isSelected();
        if(checked){
            ckbTuesday.setEnabled(false);
            ckbThursday.setEnabled(false);
        }
        else if(!checked && !ckbMonday.isSelected() && !ckbWednesday.isSelected()){
            ckbTuesday.setEnabled(true);
            ckbThursday.setEnabled(true);
        }
    }//GEN-LAST:event_ckbFridayStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox ckbFriday;
    private javax.swing.JCheckBox ckbMonday;
    private javax.swing.JCheckBox ckbNoPrefrence;
    private javax.swing.JCheckBox ckbThursday;
    private javax.swing.JCheckBox ckbTuesday;
    private javax.swing.JCheckBox ckbWednesday;
    private javax.swing.JComboBox cmbFirstPref;
    private javax.swing.JComboBox cmbSecondPref;
    private javax.swing.JComboBox cmbThirdPref;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JFormattedTextField ftxtCapacity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
